---
title: "Application for RTMD award" 
author: "Kendra, Claire, and Chris"
date: "`r lubridate::today()`"
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---   


### Project Title: Using risk terrain modeling to understand environmental factors associated with alcohol relapse

### Project Description (750 words or less) 
<!--we also have the option to upload supporting file, maybe this could be a preregistration?--><!--CP: great idea!-->
Our research aims to enhance continuing care treatment for substance use disorders by automating the delivery of personalized, adaptive recovery support. Ideally, this support is designed to help individuals monitor their current and future risk of relapse and adjust their behaviors and support systems accordingly.

We developed a machine learning model using two distinct types of sensing data: geolocation and daily ecological momentary assessments (EMA). This model captures the dynamic and highly individualized relapse-risk trajectories of 146 participants in early recovery from alcohol use disorder over a three-month period. Our results show that next-day drinking lapses can be predicted with high accuracy (area under the ROC curve = 0.90). We also assessed the most influential factors contributing to predictions for each participant on each day and found that time spent in locations participants subjectively rate as risky for their recovery consistently emerged as a top predictor of relapse. This suggests a strong link between time spent in self-determined high-risk environments and relapse. However, relapses also frequently occur in locations participants rate as "low" or "no" risk, indicating that perhaps less salient or harder to self-assess environmental factors may play a significant role in relapse risk. 

In this study, we aim to apply risk terrain modeling to better characterize environmental risk factors associated with relapse in both subjectively-rated "high" and "low" risk locations. For instance, self-rated high-risk locations may have more overt alcohol-related cues (e.g., bars, liquor stores), while low-risk locations may contain subtler environmental triggers. By identifying and comparing these factors, we hope to uncover nuanced contributors to relapse risk and improve the precision of recovery support recommendations.

Ultimately, this work seeks to inform the development of adaptive interventions that respond to environmental risk in real time. By integrating these insights into machine learning algorithms, we can enhance the personalization and effectiveness of continued monitoring and support systems.


### Briefly: What are the expected IMPLICATIONS for local/regional/national practice or policy? 
Our findings have significant implications for clinical practice and public health policy. By identifying environmental risk factors associated with relapse, especially those in locations individuals perceive as low risk, we can improve the accuracy of predictive models and the effectiveness of interventions. Clinicians could use these insights to tailor recovery plans that account for environmental influences, particularly those less salient to the individual. At a policy level, mapping geographic contributors to relapse risk could influence health insurance coverage of these continuing monitoring and support systems as they go to market, such as location-based guaranteed intervention access through public insurers like Medicaid. 

### Briefly: Where do you want to go next with this project? 
We plan to use risk terrain modeling to identify specific environmental features that contribute to relapse risk in both high and low self-rated risk locations. These findings will help us improve our machine learning models by adding new risk-relevant features that may have been previously missed. This will ultimately enable us to make more precise predictions of relapse risk based on location data.

Additionally, we aim to develop and test adaptive interventions that respond to environmental risk in real time. For example, if a location has features consistent with a high risk location that participants might subjectively rate as high risk, an intervention might focus on recommending they avoid that location. However, if a location has features consistent with a high risk location that participants might not subjectively rate as high risk, an intervention might focus on increasing awareness of the environmental cues present in that location and how to manage them.

By advancing our understanding of environmental risk and integrating it into predictive intervention frameworks, we hope to contribute to more effective, personalized, and scalable approaches to supporting long-term recovery from substance use disorders.